### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by luoww1992** [isarandi/cameralib#1]
q1, is it for metrabs args?
q2, how to use it?
q3, if i get intri and extri from easymocap, i need to process these again ?

**Comment by isarandi** [comment]
For now, I won't have time to write docs beyond what is in the code as comments. You can see examples of how it is used in my `poseviz` repo and in the `metrabs` repo.
You should be able to reuse the intrinsics and extrinsics obtained from other sources, as long as it's following the same convention.
